MADMAC=$(JAGPATH)/bin/mac
ALN=$(JAGPATH)/bin/aln
CC=m68k-atari-mint-gcc
LIB=$(JAGPATH)/lib/lib
INCL=-I$(JAGPATH)/lib/include
JCP=jcp
VJ=virtualjaguar

STADDR=4000
ALNFLAGS=-a $(STADDR) x x -rq -v -w -y $(LIB)
MACFLAGS=-fb -v
CFLAGS=-mc68000 -Wall -fomit-frame-pointer -O2 -msoft-float -funroll-loops $(INCL)
