MADMAC=$(JAGPATH)/src/rmac/rmac
ALN=$(JAGPATH)/src/rln/rln
CC=m68k-atari-mint-gcc
LIB=$(JAGPATH)/lib/lib
INCL=-I$(JAGPATH)/lib/include

STADDR=4000
ALNFLAGS=-a $(STADDR) x x -rq -w -y $(LIB)
MACFLAGS=-fb -v
CFLAGS=-mc68000 -Wall -fomit-frame-pointer -O2 -msoft-float -funroll-loops $(INCL)
